#!/usr/bin/env bash
# =============================================================
# asset-editor deploy script (dev VPS).
#
# Called by .github/workflows/deploy.yml over SSH AFTER the workflow has reset
# this repo's server checkout to origin/main. Generates .env from the env vars
# the workflow passes in, pulls the image from GHCR, and (re)starts the service.
# Runs in the repo checkout dir (e.g. /opt/asset-editor).
#
# Env in: IMAGE_TAG, GHCR_PAT, GHCR_USER, MINIO_ENDPOINT_URL, MINIO_ACCESS_KEY,
#         MINIO_SECRET_KEY, MINIO_BUCKET, ASSET_EDITOR_PORT
# =============================================================
set -euo pipefail

COMPOSE="docker compose -f docker-compose.deploy.yml"

echo "=== asset-editor deploy at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="

# 1. Code already synced by the workflow (git reset --hard origin/main); doing
#    the reset here would rewrite the file bash is executing mid-run.
echo "[1/4] Code synced by workflow."

# 2. Generate .env consumed by docker-compose.deploy.yml.
echo "[2/4] Generating .env..."
cat > .env <<EOF
# Auto-generated by scripts/deploy.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT edit by hand — overwritten on next deploy. Change values in the
# GitHub Environment "dev" (secrets/variables) and re-deploy.
IMAGE_TAG=${IMAGE_TAG}
ASSET_EDITOR_PORT=${ASSET_EDITOR_PORT:-7777}
MINIO_ENDPOINT_URL=${MINIO_ENDPOINT_URL:-}
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-}
MINIO_BUCKET=${MINIO_BUCKET:-fairytale-assets}
EOF
# Escape literal $ in values so compose doesn't read them as var references.
# (Shell vars were already expanded by the heredoc above.)
sed -i '/^[^#]/s/\$/\$\$/g' .env
echo "  .env generated."

# 3. Login to GHCR and pull the freshly built image.
echo "[3/4] Pulling image from GHCR..."
echo "${GHCR_PAT}" | docker login ghcr.io -u "${GHCR_USER:-OtabekEshpulatov}" --password-stdin
$COMPOSE pull

# 4. Recreate the service and reclaim old image layers.
echo "[4/4] Starting asset-editor..."
$COMPOSE up -d
docker image prune -f >/dev/null 2>&1 || true

echo "=== deploy complete ==="
$COMPOSE ps
